### ISSUE TITLE
TinyMCE on iFrame example page expires on 20 November 2020

### ISSUE THREAD

**Issue by mwakizaka** [saucelabs/the-internet#63]
<img width="1028" alt="Screen Shot 2020-11-17 at 8 58 15" src="https://user-images.githubusercontent.com/21286384/99322317-0bf82180-28b3-11eb-8a24-5ab9223e9fad.png">

Not sure but it is likely required to upgrade an account for TinyMCE?
http://the-internet.herokuapp.com/iframe

**Comment by pablopaul** [comment]
I get the same message on `Your access to TinyMCE will expire on 30 November 2020`.

@christian-bromann @tourdedave do you have to solve this or can I do something from my end?

**Comment by tourdedave** [comment]
It looks like there's a community account that you can register for
that's free: https://www.tiny.cloud/pricing

Cheers,
Dave H

On November 17, 2020, Virginia Ladd <notifications@github.com> wrote:
> I get the same message on Your access to TinyMCE will expire on 30
> November 2020.
>
> @christian-bromann <https://github.com/christian-bromann>
> @tourdedave <https://github.com/tourdedave> do you have to solve this

> or can I do something from my end?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/saucelabs/the-internet/issues/63#issuecomment-
728848158>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AADPTMOC3NIYQAOOBE5J3CLSQJIOHANCNFSM4TX3HLXQ>.

**Comment by pablopaul** [comment]
@tourdedave thanks Dave - do you have a specific Saucelabs open source email account I could use for registering? otherwise it would be tight to my personal email which does not make sense in the long run.

**Comment by tourdedave** [comment]
I don't. Maybe @christian-bromann or @diemol have some input here.

**Comment by christian-bromann** [comment]
I will update the account shortly.

**Comment by christian-bromann** [comment]
Fixed with https://github.com/saucelabs/the-internet/commit/a59a0c5441bf23f8fb43383da060fedf1f52e986 , I will have to request push credentials first before I can update the app.
